function ActivityHome() {
  return (
    <>
      <div className="activity-card-wrapper">
        <h2>Home</h2>
        <div className="home-card">
            <h3>Welcome to Optimistic Weather</h3>
            <p>
              Optimistic Weather is a suggestion app determined on the weather
              focused on keeping you positive.
            </p>
            <p>
              Start off by selecting a location with the search menu in the top
              right.
            </p>
        </div>
        <div className="home-card">
        <h3>Activities</h3>
        <p>
          A curated selection of suggestions tailored specifically for the
          weather at your selected location.
        </p>
        <p>
          You are able to change the list of suggestions to a different weather
          type or duration with either of the drop down menues.
        </p>
        </div>
        <div className="home-card">
        <h3>Events</h3>
        <p>
          A list of event suggestions for your selected location pulled from the
          eventfinda website.
        </p>
        {/* more info to go here when implemented */}
        </div>
        <div className="home-card">
        <h3>Clothing</h3>
        <p>
          Suggested clothing and items based on the weather at your selected
          location.
        </p>
        </div>
        <div className="home-card">
        <h3>AI</h3>
        <p>
          If you're feeling more creative feel free to chat to our AI assistant
          to get some more interesting suggestions.
        </p>
        <p>
          We will get you started with a custom prompt generated with your
          selected location and current weather.
        </p>
        <p>
          note: All AI suggestions are generated by an AI model and should be
          understood and followed with caution.
        </p>
        </div>
      </div>
    </>
  )
}

export default ActivityHome
