/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async (knex) => {
  // Deletes ALL existing entries
  await knex('activities').del()
  await knex('activities').insert([
    {
      activity_id: 1,
      name: 'Fishing 🎣',
      weather: 'cloudy',
      type: 'half day or longer',
      optionaldetails: 'Spend a relaxing day out by the lake fishing.',
    },
    {
      activity_id: 2,
      name: 'Hiking ⛰️',
      weather: 'sunny',
      type: 'full day',
      optionaldetails: 'Make sure to tell someone you are going for a hike!',
    },
    {
      activity_id: 3,
      name: 'Go see a movie 🍿',
      weather: 'rain',
      type: 'short',
      optionaldetails: 'Take a look at whats showing at your local cinema.',
    },
    {
      activity_id: 4,
      name: 'Beach 🏖️',
      weather: 'sunny',
      type: 'half day or longer',
      optionaldetails: 'Wear sunscreen.',
    },
    {
      activity_id: 5,
      name: 'Code 🖥️',
      weather: 'cloudy',
      type: 'multi day',
      optionaldetails: 'Careful you dont hurt yourself.',
    },
    {
      activity_id: 6,
      name: 'Picnic 🧺',
      weather: 'sunny',
      type: 'half day or longer',
      optionaldetails: 'Pack a lunch and enjoy the outdoors.',
    },
    {
      activity_id: 7,
      name: 'Museum Visit 🖼️',
      weather: 'rain',
      type: 'half day',
      optionaldetails: 'Explore history and culture.',
    },
    {
      activity_id: 8,
      name: 'Indoor Rock Climbing 🧗',
      weather: 'rain',
      type: 'short',
      optionaldetails: 'Challenge yourself with different climbing walls.',
    },
    {
      activity_id: 9,
      name: 'Reading at the Library 📚',
      weather: 'cloudy',
      type: 'half day',
      optionaldetails: 'Find a quiet spot and get lost in a book.',
    },
    {
      activity_id: 10,
      name: 'Gardening 🌱',
      weather: 'sunny',
      type: 'multi day',
      optionaldetails: 'Grow your own vegetables and herbs.',
    },
    {
      activity_id: 11,
      name: 'Board Games 🎲',
      weather: 'rain',
      type: 'short',
      optionaldetails: 'Great way to spend time indoors with friends.',
    },
    {
      activity_id: 12,
      name: 'Photography 📸',
      weather: 'sunny',
      type: 'half day or longer',
      optionaldetails: 'Capture the beauty of nature.',
    },
    {
      activity_id: 13,
      name: 'Coffee Tasting ☕',
      weather: 'cloudy',
      type: 'short',
      optionaldetails: 'Discover new flavors and brewing methods.',
    },
    {
      activity_id: 14,
      name: 'Bird Watching 🐦',
      weather: 'sunny',
      type: 'half day',
      optionaldetails: 'Peaceful observation of local wildlife.',
    },
    {
      activity_id: 15,
      name: 'Yoga 🧘',
      weather: 'cloudy',
      type: 'short',
      optionaldetails: 'Find your inner peace and improve flexibility.',
    },
    {
      activity_id: 16,
      name: 'Stargazing 🔭',
      weather: 'clear',
      type: 'night',
      optionaldetails: 'Explore the night sky and learn about constellations.',
    },
    {
      activity_id: 17,
      name: 'Kayaking 🛶',
      weather: 'sunny',
      type: 'half day',
      optionaldetails: 'Enjoy the water and the scenic views around you.',
    },
    {
      activity_id: 18,
      name: 'DIY Crafts 🛠️',
      weather: 'rain',
      type: 'multi day',
      optionaldetails: 'Create something unique with your own hands.',
    },
    {
      activity_id: 19,
      name: 'Cooking Class 🍳',
      weather: 'cloudy',
      type: 'short',
      optionaldetails: 'Learn new recipes and cooking techniques.',
    },
    {
      activity_id: 20,
      name: 'Ice Skating ⛸️',
      weather: 'snow',
      type: 'short',
      optionaldetails: 'Fun activity for all skill levels.',
    },
    {
      activity_id: 21,
      name: 'Pottery Making 🏺',
      weather: 'cloudy',
      type: 'half day',
      optionaldetails: 'Get your hands dirty and create your own pottery.',
    },
    {
      activity_id: 22,
      name: 'Biking 🚴',
      weather: 'sunny',
      type: 'full day',
      optionaldetails: 'Explore the city or countryside on two wheels.',
    },
    {
      activity_id: 23,
      name: 'Wine Tasting 🍷',
      weather: 'cloudy',
      type: 'short',
      optionaldetails: 'Discover and enjoy a variety of wines.',
    },
    {
      activity_id: 24,
      name: 'Snowboarding 🏂',
      weather: 'snow',
      type: 'full day',
      optionaldetails: 'Hit the slopes for some winter fun.',
    },
    {
      activity_id: 25,
      name: 'Visit a Zoo 🐘',
      weather: 'sunny',
      type: 'half day',
      optionaldetails: 'Learn about different animals and their habitats.',
    },
    {
      activity_id: 26,
      name: 'Sailing 🚤',
      weather: 'sunny',
      type: 'full day',
      optionaldetails: 'Experience the joy of sailing on open water.',
    },
    {
      activity_id: 27,
      name: 'Spa Day 💆',
      weather: 'rain',
      type: 'half day',
      optionaldetails: 'Relax and rejuvenate with a day at the spa.',
    },
    {
      activity_id: 28,
      name: 'Archery 🏹',
      weather: 'cloudy',
      type: 'short',
      optionaldetails: 'Test your precision and focus.',
    },
    {
      activity_id: 29,
      name: 'Scuba Diving 🤿',
      weather: 'sunny',
      type: 'full day',
      optionaldetails: 'Explore underwater worlds.',
    },
    {
      activity_id: 30,
      name: 'Art Gallery 🎨',
      weather: 'rain',
      type: 'half day',
      optionaldetails: 'Immerse yourself in the world of art.',
    },
    {
      activity_id: 31,
      name: 'Mountain Biking 🚵',
      weather: 'sunny',
      type: 'full day',
      optionaldetails: 'Tackle challenging trails and enjoy the outdoors.',
    },
    {
      activity_id: 32,
      name: 'Hot Air Balloon Ride 🎈',
      weather: 'clear',
      type: 'short',
      optionaldetails: 'Experience breathtaking views from above.',
    },
    {
      activity_id: 33,
      name: 'Surfing 🏄',
      weather: 'sunny',
      type: 'half day',
      optionaldetails: 'Catch some waves at your local beach.',
    },
    {
      activity_id: 34,
      name: 'Ghost Tour 👻',
      weather: 'cloudy',
      type: 'night',
      optionaldetails:
        'Explore haunted locations and learn about their history.',
    },
    {
      activity_id: 35,
      name: 'Skydiving 🪂',
      weather: 'clear',
      type: 'short',
      optionaldetails: 'Experience the thrill of free fall.',
    },
    {
      activity_id: 36,
      name: 'Rock Climbing 🧗‍♂️',
      weather: 'sunny',
      type: 'half day',
      optionaldetails:
        'Challenge yourself with a natural rock climbing experience.',
    },
    {
      activity_id: 37,
      name: 'Paddle Boarding 🏄‍♀️',
      weather: 'sunny',
      type: 'short',
      optionaldetails: 'Enjoy the calmness of the water while paddle boarding.',
    },
    {
      activity_id: 38,
      name: 'Camping ⛺',
      weather: 'clear',
      type: 'multi day',
      optionaldetails:
        'Connect with nature and spend a few nights under the stars.',
    },
    {
      activity_id: 39,
      name: 'Frisbee Golf 🥏',
      weather: 'sunny',
      type: 'half day',
      optionaldetails: 'A fun and relaxing way to spend the day outdoors.',
    },
    {
      activity_id: 40,
      name: 'Potluck Dinner 🍲',
      weather: 'clear',
      type: 'short',
      optionaldetails:
        'Gather friends and family for a meal where everyone contributes.',
    },
    {
      activity_id: 41,
      name: 'Salsa Dancing 💃',
      weather: 'clear',
      type: 'night',
      optionaldetails: 'Feel the rhythm and enjoy an evening of salsa dancing.',
    },
    {
      activity_id: 42,
      name: 'Kite Flying 🪁',
      weather: 'windy',
      type: 'short',
      optionaldetails: 'Take advantage of the windy weather to fly a kite.',
    },
    {
      activity_id: 43,
      name: 'Bird Making 🐦',
      weather: 'sunny',
      type: 'half day',
      optionaldetails:
        'Craft your own birdhouse or feeder to attract local birds.',
    },
    {
      activity_id: 44,
      name: 'Astronomy Night 🔭',
      weather: 'clear',
      type: 'night',
      optionaldetails: 'Join a local astronomy club for a night of stargazing.',
    },
    {
      activity_id: 45,
      name: 'Herb Gardening 🌿',
      weather: 'sunny',
      type: 'multi day',
      optionaldetails:
        'Start your own herb garden at home or in a community garden.',
    },
    {
      activity_id: 46,
      name: 'Watercolor Painting 🎨',
      weather: 'rain',
      type: 'half day',
      optionaldetails: 'Experiment with watercolor techniques on a rainy day.',
    },
    {
      activity_id: 47,
      name: 'Volunteering 🤲',
      weather: 'cloudy',
      type: 'full day',
      optionaldetails:
        'Give back to the community by volunteering at a local organization.',
    },
    {
      activity_id: 48,
      name: 'Rollerblading 🛼',
      weather: 'sunny',
      type: 'short',
      optionaldetails:
        'Glide through the park or along the beachfront on rollerblades.',
    },
    {
      activity_id: 49,
      name: 'Chess in the Park ♟️',
      weather: 'cloudy',
      type: 'short',
      optionaldetails:
        'Challenge friends or locals to a game of chess in the park.',
    },
    {
      activity_id: 50,
      name: 'Aquarium Visit 🐠',
      weather: 'rain',
      type: 'half day',
      optionaldetails: 'Discover marine life and ecosystems at an aquarium.',
    },
  ])
}
